#ifndef NUMBERGENERATOR_GLOBAL_H
#define NUMBERGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NUMBERGENERATOR_LIBRARY)
#  define NUMBERGENERATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NUMBERGENERATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NUMBERGENERATOR_GLOBAL_H
